### ISSUE TITLE
Update unit tests

### ISSUE THREAD

**Issue by t-lini** [quadrama/DramaAnalysis#106]
check which functions and options need to be added/updated, organize files using `testthat()` and `context()` to make the tests more readable

- [x] configuration
- [x] data (add tests for base dictionary)
- [x] dictionary statistics (add tests for base dictionary, new function `filterByDictionary()`)
- [x] dictionary statistics (add more tests for `regroup()` when #109 is fixed
- [x] drama head
- [x] drama tail
- [x] frequencytable (`by`-option)
- [x] limit figures (new option `other`, new function `filterMentioned()`)
- [x] presence
- [x] tfidf
- [x] utility
- [x] utteranceStatistics
- [x] add tests for figures.R, fix #114 
- [x] add tests for personnel exchange #57 
- ~~[ ] figures: add tests for `rankFiguresByAppearance()`?~~
- ~~[ ] dictionary statistics: add tests for `enrichDictionary()`? (dependent on pre-trained word2vec model)~~
- [x] save.R: add tests after #123 
- [x] update tests for base_dictionary

**Comment by t-lini** [comment]
How should the figures-dataframe look like as an input for `rankFiguresByAppearance()`? Maybe we should include an example in the documentation (for both rank-functions).

**Comment by t-lini** [comment]
Closing this cluttered issue in favor of #130 for 3.x
