### ISSUE TITLE
Improve meta data export

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaAnalysis#29]
multiple authors or dates

- [x] Dates are now a feature of the `Drama` FS and thus accessible directly
- [x] `Author` or `Translator` annotations can be extracted using `getAnnotations()` (verification needed)

**Comment by nilsreiter** [comment]
- [x] Dates are now a feature of the `Drama` FS and thus accessible directly
- [ ] `Author` or `Translator` annotations can be extracted using `getAnnotations()` (verification needed)

**Comment by nilsreiter** [comment]
Author can be extracted.
