### ISSUE TITLE
Update meta information

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaAnalysis#65]
- [x] Installation instructions - README.md
- [x] Dependencies - README.md
- [x] Regular release - CONTRIBUTING.md
